### ISSUE TITLE
[enhancement] support for postgres db instead of local db file

### ISSUE THREAD

**Issue by blysik** [boivie/lovebeat#9]
To be able to install this application into a PaaS like Heroku, it would be awesome if you supported postgres.  This would also allow higher availability via multiple lovebeat front-ends.

**Comment by boivie-at-sony** [comment]
We have previously discussed how to provide some sort of high availability (which would require some sort of external database). 

Lovebeat is not a traditional stateless frontend which makes it non-trivial to break out the storage to an external RDBMS and start multiple lovebeat daemons serving clients. This is because lovebeat loads the entire database into ram (much like redis) and expire services in the background based on this data.

So there are two ways to go, as I see it:
 * making lovebeat a stateless frontend and keep all the state in a database. This makes it easy to scale out (not for performance, but for increased availability), but the database will still be a single point of failure
 * Using a leader-follower pattern where one instance is the leader and the other followers. Requests to the followers would be proxied to the leader and when the leader goes down, a new leader will be elected among the followers. We would typically use some sort of multi-master database for this (etcd, consul, ...) and it would provide us with better availability as there would be no single point of failure.

I'm leaning towards the second solution as that would also allow us to work with the data in RAM. That's almost a requirement when we have a huge amount of services.

**Comment by blysik** [comment]
Aha!  Okay, then yes, generalizing my request to 'enable some sort of high availability' is more accurate.  

Knowing what I know now about lovebeat, I will probably move my installation to a more traditional static VM, rather than a PaaS which has a certain amount of flux.

**Comment by boivie-at-sony** [comment]
Fast forward almost one year, and this is what we have now:
 * The database file can now be downloaded from/uploaded to Amazon S3 for persistence for ephemeral hosts. The rationale and documentation can be found at http://lovebeat.readthedocs.io/en/latest/advanced.html#database-on-s3. Not using Amazon? Let me know.
 * We also allow having two lovebeats monitor each other, to allow detection of degraded service. Still no high availability, but now it's at least simple to recycle the lovebeat instance and have a new working one in case it breaks down.

So I'm closing this issue and hope that what I presented above is sufficient.
